@host = http://localhost:3025
@contentType = application/json

### Login
# @name login
POST {{host}}/usuario/sesion
Content-Type: {{contentType}}

{
	"user": "uriel.aguilera@tecmm.edu.mx",
	"pass": "123456"
}

### Get me
@token = {{login.response.body.token}}


###
GET {{host}}/personal/libre/
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

###
GET {{host}}/personal/libre
Content-Type: {{contentType}}
Authorization: Bearer {{token}}